#!/usr/bin/env python3
"""
Generate SystemVerilog test vectors for the GSAF smoke testbench.
Uses the verified golden model as reference. Run:
    python model/gen_vectors.py > tb/tb_vectors.svh
"""
import random
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from golden_model import (modexp, modinv_divsteps, check_inputs,
                          STATUS_OK, STATUS_NOT_INVERTIBLE,
                          STATUS_INVALID_INPUT, STATUS_UNSUPPORTED)

WIDTH = 64
EXP_BLIND_BITS = 64
EXP_W = WIDTH + EXP_BLIND_BITS
N_RANDOM = 24

OP_MODEXP = 0x0
OP_MODINV = 0x1
OP_PQC    = 0xD   # reserved -> STATUS_UNSUPPORTED


def main() -> None:
    rng = random.Random(0x5EED)
    rows = []  # (opcode, a, b, m, exp_status, exp_result)

    # directed: error cases
    rows.append((OP_MODEXP, 1, 1, 0, STATUS_INVALID_INPUT, 0))            # m = 0
    rows.append((OP_MODEXP, 1, 1, 0x10, STATUS_INVALID_INPUT, 0))         # m even
    rows.append((OP_MODEXP, 0xFF, 1, 0x0F, STATUS_INVALID_INPUT, 0))      # a >= m
    rows.append((OP_MODINV, 9, 0, 9, STATUS_INVALID_INPUT, 0))            # a >= m
    rows.append((OP_PQC,    1, 1, 5, STATUS_UNSUPPORTED, 0))              # reserved op

    # directed: zero operand / identities
    m = (1 << WIDTH) - 59  # odd
    rows.append((OP_MODEXP, 0, 0, m, STATUS_OK, modexp(0, 0, m, WIDTH)))  # 0^0
    rows.append((OP_MODEXP, 0, 5, m, STATUS_OK, 0))
    rows.append((OP_MODEXP, 1, (1 << WIDTH) - 1, m, STATUS_OK, 1))
    rows.append((OP_MODINV, 0, 0, m, STATUS_NOT_INVERTIBLE, 0))           # gcd(0,m)=m

    # directed: non-invertible (shared factor)
    rows.append((OP_MODINV, 3, 0, 9, STATUS_NOT_INVERTIBLE, 0))

    # directed: DPA exponent blinding -- d' = d + k*(m-1), m prime; the
    # blinded exponent exceeds WIDTH bits and exercises the wide B region
    P64 = (1 << 64) - 59          # prime
    for _ in range(3):
        a = rng.randrange(1, P64)
        d = rng.randrange(1 << 64)
        k = rng.randrange(1, 1 << 64)
        d_blind = d + k * (P64 - 1)
        expect = modexp(a, d_blind, P64, WIDTH, exp_bits=EXP_W)
        assert expect == pow(a, d, P64)          # blinding invariant
        rows.append((OP_MODEXP, a, d_blind, P64, STATUS_OK, expect))

    # random functional
    for _ in range(N_RANDOM):
        m = rng.randrange(3, 1 << WIDTH) | 1
        a = rng.randrange(m)
        if rng.random() < 0.5:
            e = rng.randrange(1 << WIDTH)
            rows.append((OP_MODEXP, a, e, m, STATUS_OK,
                         modexp(a, e, m, WIDTH)))
        else:
            st, inv = modinv_divsteps(a, m, WIDTH)
            rows.append((OP_MODINV, a, 0, m, st, inv))

    print("// AUTO-GENERATED by model/gen_vectors.py - do not edit")
    print(f"localparam int unsigned TB_WIDTH = {WIDTH};")
    print(f"localparam int unsigned TB_EXP_W = {EXP_W};")
    print(f"localparam int unsigned N_VECTORS = {len(rows)};")
    print("typedef struct {")
    print("  logic [3:0]          opcode;")
    print(f"  logic [{WIDTH-1}:0]  a;")
    print(f"  logic [{EXP_W-1}:0]  b;")
    print(f"  logic [{WIDTH-1}:0]  m;")
    print("  logic [2:0]          exp_status;")
    print(f"  logic [{WIDTH-1}:0]  exp_result;")
    print("} tb_vec_t;")
    print("tb_vec_t vectors [N_VECTORS];")
    print("function automatic void load_vectors();")
    for i, (op, a, b, m, st, res) in enumerate(rows):
        print(f"  vectors[{i}] = '{{4'h{op:X}, {WIDTH}'h{a:X}, "
              f"{EXP_W}'h{b:X}, {WIDTH}'h{m:X}, 3'd{st}, {WIDTH}'h{res:X}}};")
    print("endfunction")


if __name__ == "__main__":
    main()
